export const DOCS = `Dev/Docs`;
export const QUARKS = `Quarks`;
export const ATOMS = `Atoms`;
export const MOLECULES = `Molecules`;
export const ORGANISMS = `Organisms`;
export const VIEWS = `Views`;
export const FEATURES = `Features`;
export const DEPRECATED = `Deprecated`;
export const USE_CASES = `Use Cases`;
